// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qghfqtwxswaxuzlypcel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnaGZxdHd4c3dheHV6bHlwY2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Nzk3MDcsImV4cCI6MjA2MTE1NTcwN30.ynKu61Ic8FlvVv3vmXYeWGvLfx3F0SX6UtZ7pm5xJ0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);